name: portfolio
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^10.0.1
  cloud_firestore: ^5.6.6
  dio: ^5.8.0+1
  duration: ^4.0.3
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flash: ^3.1.1
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage_x: ^10.2.2
  hive_ce_flutter: ^2.2.0
  internet_connection_checker_plus: ^2.7.1
  multiple_result: ^5.1.0
  platform_info: ^5.0.0
  responsive_framework: ^1.5.1
  slang_flutter: ^4.6.0
  talker_dio_logger: ^4.7.1
  talker_flutter: ^4.7.1
  talker_riverpod_logger: ^4.7.1
  velocity_x: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  riverpod_lint: ^2.6.5
  riverpod_test: ^0.1.8
  slang_build_runner: ^4.6.0
  spot: ^0.17.0
  very_good_analysis: ^7.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/